---
# tasks file for consul
- name: 'Update apt-get repo and cache'
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: 'Install unzip wget curl gnupg2'
  apt:
    name:
      - unzip
      - wget
      - curl
      - gnupg2
    state: present
    update_cache: yes
  become: yes

- name: 'Download and unarchive consul'
  become: true
  unarchive:
    src: 'https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip'
    dest: /usr/local/bin/
    remote_src: yes

- name: 'Create data_dir'
  file:
    path: /var/lib/consul
    state: directory
  become: true  

- name: 'Create conf_dir'
  file:
    path: /etc/consul.d
    state: directory
  become: true

- name: 'Setup consul config'
  template:
    src: 'consul-config'
    dest: '/etc/consul.d/config.json'
  become: true

- name: 'Setup consul service file'
  template:
    src: 'consul-service'
    dest: '/etc/systemd/system/consul.service'
  become: true

- name: 'Enable consul service'
  ansible.builtin.service:
    name: consul.service
    enabled: yes
  become: true

- name: 'Start consul service'
  ansible.builtin.service:
    name: consul.service
    state: started
  become: true  


