---
# defaults file for mongodb
mongodb_version: "4.4"
debian_packages:
  - apt-transport-https
  - curl
  - gnupg
debian:
  apt_key_url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
  apt_repository_repo: "deb{{ ' [ arch=amd64,arm64 ]' if ansible_facts.distribution == 'Ubuntu' else '' }} https://repo.mongodb.org/apt/{{ ansible_facts.distribution|lower }} {{ ansible_facts.distribution_release }}/mongodb-org/{{ mongodb_version }} {{ 'multiverse' if ansible_facts.distribution == 'Ubuntu' else 'main' }}"

