- name: 'Update apt repo and cache'
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: 'MongoDB - Import public key'
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
  become: true

- name: 'MongoDB - Add repository'
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-4.4'
    repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse'
    state: present
    update_cache: true
  become: true  

- name: 'Install mongodb'  
  apt:
    state: present
    update_cache: true    
    name: "{{ item }}"
  loop:
    - 'mongodb-org'
  become: true
  
- name: 'MongoDB - copy config file'
  template: "src=../templates/mongod.conf dest=/etc/mongod.conf"
  become: true
  notify:
    - restart mongodb     
          
- name: 'MongoDB - Running state'
  service:
    name: mongod
    state: started
  become: true  
